### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by elect86** [detekt/detekt-custom-rule-template#23]
as titled, fresh cloned, tried to run the test(s) via Idea gui:

> Execution failed for task ':test'.
> No tests found for given includes: [org.example.detekt.MyRuleSpec](--tests filter)
> Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

If I switch to running test with Idea instead:

> org.junit.runners.model.InvalidTestClassError: Invalid test class 'org.example.detekt.MyRuleSpec':
>  1. Test class should have exactly one public zero-argument constructor

>	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
	at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

> Process finished with exit code 255

**Comment by elect86** [comment]
What about running via Idea gui instead?

However, what output do you see? I have this:
> elect@5800x:~/IdeaProjects/detekt-custom-rule-template$ ./gradlew test

BUILD SUCCESSFUL in 865ms
4 actionable tasks: 2 executed, 2 up-to-date

Anyway, if I change the first test in order to make it fail:
`assertThat(findings).hasSize(2)`
I still see the very same output

**Comment by BraisGabin** [comment]
Ooops! Good catch! I can see the error now.

**Comment by BraisGabin** [comment]
I found the issue. The import of `@Test` points to JUnit4 🤦. I didn't expect that truth will import that dependency (https://github.com/google/truth/issues/333). I'm still looking for a good assertion library for kotlin. I like hamscrest but they really heavily on the function `is(...)` and on kotlin it should be quoted as `` `is`(...) ``.

**Comment by BraisGabin** [comment]
Nice idea: #25
